# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Git Quick Reference
tagline:             'A fairly simple Git reference listing'
url:                 https://comicsguy.github.io/git-ref
baseurl:             'https://comicsguy.github.io/git-ref'
paginate:            5

# About/contact
author:
  name:              Brian Plunkett
  url:               https://github.com/comicsguy
  email:             brian.plunkett@gmail.com

# Custom vars
version:             1.0.0
